Blog1/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace='users')),
    path('', include('blogs.urls', namespace='blogs')),
]

blogs/urls.py
from django.urls import path

from . import views

app_name = 'blogs'

urlpatterns = [
    # Стартовая страница (отображение всех тем)
    path('', views.index, name='index'),
    # Форма создания сообщения
    path('newpost', views.new_post_view, name='new_post'),
    # Форма редактирования сообщения
    path('editpost/<int:post_id>', views.edit_post, name='edit_post'),
]

users/urls.py
from django.urls import path
from django.contrib.auth.views import login

from . import views

app_name = 'users'

urlpatterns = [
    # Страница регистрации пользователя
    path('register/', views.register_view, name='register'),
    # Страница авторизации пользователя
    path('login/', login, {'template_name': 'users/login.html'}, name='login'),
    # Страницы завершения сеанса
    path('logout/', views.logout_view, name='logout'),
]

blogs/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Blogpost(models.Model):
    title = models.CharField(max_length=20)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, True)

    def __str__(self):
        return self.title + '(' + str(self.date_added) + ')'

users/models.py
# from django.db import models

# Create your models here.

blogs/forms.py
from django import forms
from .models import Blogpost


class BlogpostForm(forms.ModelForm):
    class Meta:
        model = Blogpost
        fields = ['title', 'text']
        labels = {'title': '', 'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 100})}

blogs/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, Http404
from django.urls import reverse
from django.contrib.auth.decorators import login_required

from .models import Blogpost
from .forms import BlogpostForm


# Create your views here.
def index(request):
    """Отображение всех тем"""
    posts = Blogpost.objects.order_by('date_added')

    context = {'blogposts': posts}
    return render(request, 'blogs/index.html', context)


@login_required
def new_post_view(request):
    """Создание нового поста"""
    if request.method != 'POST':
        form = BlogpostForm()
    else:
        form = BlogpostForm(data=request.POST)
        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.owner = request.user
            new_post.save()
            return HttpResponseRedirect(reverse('blogs:index'))
    context = {'form': form}
    return render(request, 'blogs/new_post.html', context)


@login_required
def edit_post(request, post_id):
    """Редактирование поста"""
    post = Blogpost.objects.get(id=post_id)

    # Проверка владельца поста
    if post.owner != request.user:
        raise Http404

    if request.method != 'POST':
        form = BlogpostForm(instance=post)
    else:
        form = BlogpostForm(instance=post, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('blogs:index'))
    context = {'form': form, 'post': post}
    return render(request, 'blogs/edit_post.html', context)

users/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, logout, login


# Create your views here.
def register_view(request):
    """Представление регистрации пользователя"""
    if request.method != 'POST':
        form = UserCreationForm()
    else:
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            new_user = form.save()
            auth_user = authenticate(username=new_user.username, password=request.POST['password1'])
            login(request, auth_user)
            return HttpResponseRedirect(reverse('blogs:index'))
    context = {'form': form}
    return render(request, 'users/register.html', context)


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('blogs:index'))

blogs/templates/blogs/base.html
<!DOCTYPE html>
{% load bootstrap4 %}
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Мой супер блог</title>
    {% bootstrap_css %}
    {% bootstrap_javascript %}
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
        <a href="{% url 'blogs:index' %}" class="navbar-brand h1">Мой <span class="badge badge-secondary">блог</span></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse"
                data-target="#navbarmenu" aria-controls="navbarmenu"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Схлопываемая область меню navbarmenu -->
        <div class="collapse navbar-collapse justify-content-end" id="navbarmenu">
            <ul class=" navbar-nav">
                {% if user.is_authenticated %}
                <li class="nav-item">Добро пожаловать, {{user.username}} (<a href="{% url 'users:logout' %}">Выйти</a>)</li>
                {% else %}
                <li class="nav-item"><a href="{% url 'users:login' %}" class="nav-link">Войти</a></li>
                <li class="nav-item"><a href="{% url 'users:register' %}" class="nav-link">Зарегистрироваться</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>
<p>

</p>
<div class="container">
{% block content %}

{% endblock content %}

</div>

</body>
</html>

blogs/templates/blogs/edit_post.html
{% extends "blogs/base.html" %}
{% load bootstrap4 %}

{% block content %}
<h2>Редактирование поста {{post}}</h2>

<form action="{% url 'blogs:edit_post' post.id %}" method="post" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
    <button name="submit" class="btn btn-primary">Сохранить изменения</button>
    {% endbuttons %}
</form>
{% endblock content %}

blogs/templates/blogs/index.html
{% extends "blogs/base.html" %}
{% load bootstrap4 %}

{% block content %}
<div class="card">
    {% for post in blogposts %}
    <h5 class="card-header">
        {{post.title}} <small>({{post.owner}} - {{post.date_added|date:'d M Y, h:i'}})</small>
    </h5>
    <div class="card-body">
        <p>{{post.text|linebreaks}}</p>
        {% if post.owner == user %}
        <a href="{% url 'blogs:edit_post' post.id %}">Редактировать пост</a>
        {% endif %}
    </div>
    {% empty %}
    <p>Блог полностью пуст</p>
    {% endfor %}
</div>
<p></p>
    <a href="{% url 'blogs:new_post' %}" class="btn btn-secondary">Добавить пост</a>


{% endblock content %}

blogs/templates/blogs/new_post.html
{% extends "blogs/base.html" %}
{% load bootstrap4 %}

{% block content %}
<h2>Создание нового поста</h2>

<form action="{% url 'blogs:new_post' %}" method="post" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
    <button name="submit" class="btn btn-primary">Добавить пост</button>
    {% endbuttons %}
</form>
{% endblock content %}

users/templates/users/login.html
{% extends "blogs/base.html" %}
{% load bootstrap4 %}

{% block content %}
<form method="post" action="{% url 'users:login' %}" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
    <button name="Submit" class="btn btn-primary">Войти</button>
    {% endbuttons %}
    <input type="hidden" name="next" value="{% url 'blogs:index' %}"/>
</form>
{% endblock content %}

users/templates/users/register.html
{% extends "blogs/base.html" %}
{% load bootstrap4 %}

{% block content %}
<form method="post" action="{% url 'users:register' %}" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
    <button name="Submit" class="btn btn-primary">Зарегистрировать</button>
    {% endbuttons %}
</form>
{% endblock content %}